services:
  postgres:
    image: postgres:16
    container_name: envirowatchsi-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: envirowatchsi
      POSTGRES_USER: envirowatch
      POSTGRES_PASSWORD: envirowatch123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: