package lexer

enum class TokenType {
    CITY, AREA, POLYGON, RIVER, DATE, RULE, LIST, IF, ELSE, FOR, IN, WHILE,
    STATION, TYPE, AIR, METEO, HYDRO, MIXED,

    AIR_STATION, METEO_STATION, HYDRO_STATION,

    SOURCE, STATUS, ACTIVE, INACTIVE, TEST,

    MEASUREMENT, AQI,
    TEMPERATURE, HUMIDITY, PRECIPITATION, WIND, SPEED, DIRECTION,
    WATER_LEVEL, WATER_FLOW,

    POLLUTANT, PM10, PM2_5, O3, CO, SO2,

    THRESHOLD, FLOOD_THRESHOLD, WARNING, CRITICAL,

    UNIT, AT, INTERVAL, FROM, TO, STEP,

    ID, STRING, NUMBER,

    LBRACE, RBRACE,
    LBRACKET, RBRACKET,
    LPAREN, RPAREN,
    COMMA, SEMICOLON, EQUALS,
    GREATER, LESS, GREATER_EQUAL, LESS_EQUAL, EQUAL_EQUAL, BANG_EQUAL,

    EOF
}
