name: CI

on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./EnviroWatchSI/gradlew

      - name: Run unit tests
        run: ./EnviroWatchSI/gradlew :server:test -p ./EnviroWatchSI

      - name: Publish test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: EnviroWatchSI/server/build/reports/tests/test/